### ISSUE TITLE
The program doesn't exit when "exit_now" is created.

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#1]
When file "exit_now" is created in the running directory, the program does save the results, but doesn't exit.  

In addition, if "save_now" is created, the program crashes with the following message:

Finished with User_Impinging_Jet_Profiles
At line 487 of file Main_Pro.f90 (unit = 9)
Fortran runtime error: Cannot open file 'save_now': No such file or directory

(This issue was initially raised by Muhamed in an e-mail.)

**Comment by Niceno** [comment]
I managed to resolve "exit_now" issue, but couldn't reproduce "save_now".  I ran in serial and parallel with user functions, but program always saves files and gracefully continues.

**Comment by palkinev** [comment]
confirmed
way to reproduce a bug: 
in Process/
1) make clean
2) make FORTRAN=gnu DEBUG=no CGNS_HDF5=no MPI=yes CGNS_ADF5=no
3) in divided on 2 subdomains Channel_Re_Tau_590
touch save_now; mpirun -np 2 ./Process
leads to crash

**Comment by palkinev** [comment]
pull request #13 by @Niceno solved this issue
[link](https://github.com/DelNov/T-Flows/pull/13)
