### ISSUE TITLE
New version of Time_And_Length_Scale crashes on RSM

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#106]
Dear all,

The version of Time_And_Length_Scale which Muhamed fixes recently, crashes when one tries to use RSM.  It is because the function uses `zeta % n`, but it is not allocated for RSM.

Anyone has an idea for a workaround?

    Cheers,

    Bojan

**Comment by palkinev** [comment]
This issue can be closed.
It was fixed by commit [62ee14601bc0ea474612d63c87a2af08135695e4](https://github.com/DelNov/T-Flows/blob/62ee14601bc0ea474612d63c87a2af08135695e4/Sources/Process/Turbulence/Time_And_Length_Scale.f90).
