### ISSUE TITLE
Is Swarm a good name for particle tracking?

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#107]
Dear guys,

Together with my student Mohamed Ally, I am implementing Lagrangian particle tracking method.  As a part of it, we introduce a new module called `Particles_Mod` at this moment.  This module introduces two new types: `Particle_Type` for a single particle, and `Swarm_Type`, for many particles together.

Is this name OK for everyone?  Swarm is usually used for flying insects, swarm of bees, crickets, etc, but also for flying rodents, swarm of bats for instance.  I saw swarm sand being used too, for example here: https://vimeo.com/88696709

**Comment by mhadziabdic** [comment]
It sounds cool to me, as long as OpenFOAM is not using it :).

**Comment by Niceno** [comment]
OK, it is already called Swarm in the `development_branch`, so I take the freedom to close the issue.
