### ISSUE TITLE
User functions do not work

### ISSUE THREAD

**Issue by mhadziabdic** [DelNov/T-Flows#108]
User functions for most of the cases (Backstep, Impinging jet, ...) do not work because Mod Flow does not exist any more. Is there some quick fix?

Regards,

Muhamed.

**Comment by Niceno** [comment]
Yes, this is part of re-factoring which will eventually lead to multiple materials.  I am working on the fix right now.  I don't see a quick fix :-(

**Comment by Niceno** [comment]
I almost fixed it.

**Comment by Niceno** [comment]
I believe it was fixed with last pull request I did and Muhamed accepted.
