### ISSUE TITLE
Bulk velocity at inflow is not correctly calculated if density is diff. than 1

### ISSUE THREAD

**Issue by mhadziabdic** [DelNov/T-Flows#112]
In Initialize_Variables.f90 in line 
330      print '(a29,es12.5)', ' # Average inflow velocity : ', bulk % mass_in &
                                                             / area
density is missing to get correct bulk velocity at inflow. It should be like this

330      print '(a29,es12.5)', ' # Average inflow velocity : ', bulk % mass_in &
                                                             / (density * area)

**Comment by Niceno** [comment]
Indeed!

**Comment by Niceno** [comment]
I believe Muhamed fixed this :-)
