### ISSUE TITLE
I think I merged into release_branch by mistake :-(

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#122]
Dear all,

Muhammed Aly was implementing particle tracking in the `development_branch` which we created, but it seems that I merged his changes into the `release_branch`.  I apologize :-( 

It shouldn't do any harm though, the only difference you will see is that `Main_Pro.f90` now uses `Swarm_Mod`

**Comment by Niceno** [comment]
I checked my environment with `git branch -a`, and it looks like this:

```
* development_branch
  release_branch
  remotes/origin/HEAD -> origin/release_branch
  remotes/origin/development_branch
  remotes/origin/muhammmedaly_particle_tracking
  remotes/origin/niceno_refactoring
  remotes/origin/release_branch

```
Should I set `remotes/origin/HEAD` to point to `development_branch` to make sure that pushes don't go to the `release_branch` ?

**Comment by palkinev** [comment]
There are a bunch of methods to do this.

1) Via git website we can set "development_branch" as default branch.
Thus command "git push origin", where "origin" points to https://github.com/DelNov/ repository,
should use secondary branch by default. 

2) Whenever you use "git push" add "--dry-run" option.
It does everything like ordinary "git push", including output, except actual data transfer.

3) Edit git configuration for your PC [I have not tested this option myself, thus, I do not recommend this]
https://stackoverflow.com/a/948397

**Comment by Niceno** [comment]
Thanks!
