### ISSUE TITLE
issue with gmsh mesh conversion

### ISSUE THREAD

**Issue by palkinev** [DelNov/T-Flows#162]
Unfortunately I can not successfully convert .msh in Tests/Vof/ dir.
gmsh version: 4.1.3
T-Flows dev branch commit used: 6d107a6a59851fc8bc26a9d0bc3a365670469852

I have included the whole procedure I used in this [video](https://www.dropbox.com/s/fdygcfnoidxsf27/123_c.mp4?dl=0) (better to watch it on PC).

Since the issue in the video was [line 86](https://github.com/DelNov/T-Flows/blob/6d107a6a59851fc8bc26a9d0bc3a365670469852/Sources/Convert/Load_Msh.f90#L86) in Load_Msh.f90, I edited it myself:
`read(line % tokens(4), *) n_elem` -> `read(line % tokens(2), *) n_elem`
but it was not enough.

**Comment by Niceno** [comment]
The recommened gmsh versio to use is 4.4.1 (stable release, as they call it).  The file format between 4.1.7 and 4.4.1 is different, although file versions wouldn't suggest so.

**Comment by palkinev** [comment]
I can confirm that downloading gmsh 4.4.1 64-bit version from
http://gmsh.info/#Download
solved my issue.
