### ISSUE TITLE
Turbulence model naming inconsistencies

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#18]
When performing k-eps-zeta-f in unsteady mode we call it HYBRID_K_EPS_ZETA_F.  But when running k-eps in unsteady mode (in the sense to gather statistics) we call it K_EPS and have extra option URANS.  Furthermore, for RSM-base models we don't have anything special (if I am not mistaken)

Can we introduce a better consistency here?  I would suggest that we have pure models: K_EPS, K_EPS_ZETA_F, HANJALIC_JAKIRLIC and REYNOLDS_STRESS, but if we want to run them in unsteady mode to gather statistics, we add option `turbulence_statistiscs .eq. YES`

Hence, we would have three options to define turbulence modeling strategy:
- `turbulence_model`
- `turbulence_model_variant`  currently has many variants, but I would raise it in another issue
and we also introduce:
- `turbulence_statistics`           
The latter one could be YES or NO, automatically set to YES for LES, DNS and DES, for others read should be specified from the control file.

Any thoughts, comments or suggestions?

**Comment by mhadziabdic** [comment]
Agree. This makes sense. Just to be careful with allocation and restart files for this option.
