### ISSUE TITLE
Channel flow RANS computation, pressure issue

### ISSUE THREAD

**Issue by mhadziabdic** [DelNov/T-Flows#22]
Rans Channel flow computations is producing high pressure that is homogeneously distributed over cells and number of iterations for pressure is never going to zero even computation converges. It is 14-15 iterations. Also monitoring file shows that pressure is increasing but since gradient of pressure is zero it does not affect velocity field.

**Comment by Niceno** [comment]
Dear Hamo,

Could you please specify which case, there are three channels in our code:
```
- Channel_Re_Tau_590
- Channel_Re_Tau_590_Rsm 
- Channel_Re_Tau_590_Wall_Function
```
?

**Comment by mhadziabdic** [comment]
It is the first one. I plan to merge all in one directory Channel_Re_Tau_590.

**Comment by Niceno** [comment]
Hmm ... I am not quite sure what to do here.  The reason for this behavior lies in the new implementation of the residuals ... they are now relative to values being computed.  Since pressure correction tends to zero with iterations, the relative errors are divided by very small values and thus number of iterations in the solver never fall to zero.  I will think about it a bit more.

**Comment by mhadziabdic** [comment]
Boki nemam nista protiv, ovo je svakako samo u slucaju kada imamo kanal sa periodic boundary, jel tako? Jedino da ne bude zbunjenosti kod usera kada vide linearan rast pritiska tokom false time marching.
 Zasto sada imamo minimalno 3 iteracije unutar vremenskog koraka, ima li neki poseban razloga za to?

**Comment by mhadziabdic** [comment]
Sorry for witting in Bosnian. I do not mind to keep it as it it since this pressure issue appears only for periodic channel flow, right? My only concern is that some users might be confused with pressure linearly increasing with false time marching. 
Why we keep now 3 iterations within time step even tolerance is satisfied?

**Comment by Niceno** [comment]
We have (at least) three iterations per time step because of the newly introduced parameters: `MIN_SIMPLE_ITERATIONS` and `MAX_SIMPLE_ITERATIONS`.  The former one has a default value of three, but it can be set in control file to zero.

I will look into this issue some more, I didn't realize pressure was increasing  =:-o

**Comment by mhadziabdic** [comment]
Here is pressure monitoring values. It looks quite random. This is from
channel flow comp.

Assoc. Prof. Muhamed Hadziabdic
Mech. Engineering Program Coordinator
Faculty of Engineering and Natural Sciences
International University of Sarajevo
Hrasnicka cesta 15, 71210, Ilidza, Sarajevo

mob. +387 61 228 489
mail: mhadziabdic@ius.edu.ba

**Comment by Niceno** [comment]
I fixed this issue, but couldn't create a separate pull request, it will go together with resolution of issue #25.

I did as follows.  In function `Normalized_Residuals` (in `Solvers_Mod`) I am checking the absolute value of error and absolute value of variable being solved.  If both are smaller than 1e-9 (constant called `NANO`), the normalization is not performed, and residual is set to 1e-12 (constant called `PICO`)  With this change, number of iterations for pressure is almost always zero, and the monitored values for pressure are in the nanoscopic range (less than 1e-8).

Hamo, please check if this solution works for you.

**Comment by mhadziabdic** [comment]
Great!

I have another issue with temperature equation when periodic boundary is
used. Everything goes fine when I run computation in one shot, but once I
use restart file temperature is decreasing, probably as result of this
User_Source function. Why, I do not know.
I modified Source.f90 in User_Mod directory in Process, but not in the case
directory. Could this somehow be a problem?

I also found one bug in Update_Boundary_Values.f90. Maybe you can fix it
and add to this already created push. It is this line:

166           if(Grid_Mod_Bnd_Cond_Type(grid,c2) .eq. WALLFL) then
167             t % n(c2) = t % n(c1) + t % q(c2) * grid % wall_dist(c1)
&
168                          / (con_wall(c1) * capacity)

This wall distance was missing.

I checked and both wall and wall_flux is working properly for both course
and fine mesh (y_plus > 30 and y_plus < 5)

Regards,

Muhamed.

Assoc. Prof. Muhamed Hadziabdic
Mech. Engineering Program Coordinator
Faculty of Engineering and Natural Sciences
International University of Sarajevo
Hrasnicka cesta 15, 71210, Ilidza, Sarajevo

mob. +387 61 228 489
mail: mhadziabdic@ius.edu.ba
