### ISSUE TITLE
When LES is run, simulation crash due to double allocation of u % filt variable

### ISSUE THREAD

**Issue by mhadziabdic** [DelNov/T-Flows#27]
Both Allocate_Statistics.f90 and Allocate_Variables.f90 try to allocate u % filt which cause the simulation to crash. I am not sure if this is solved by new Bojan implementations of model names.

**Comment by Niceno** [comment]
Actually, in the current version this "filt" arrays were removed since they were used only locally in one function.  Are you sure you are using the latest version of the code?

**Comment by Niceno** [comment]
Please specify which case did you run?

**Comment by Niceno** [comment]
I think this issue can be closed.  It is not the ultimate resolution of all problems with LES, but other problems will be raised by separate "issues"
