### ISSUE TITLE
Wall distance

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#39]
Dear guys,

Is it possible that we could compute wall distance in the Process simply using this: https://www.cfd-online.com/Wiki/Transport_equation_based_wall_distance_calculation

?

**Comment by palkinev** [comment]
I think this method is valid, but it seems we have to prescribe tolerance first before solving this equation.
And depending on this value it can take more or less time to convert mesh.

Thus, before starting this procedure it seems we **have to know** lowest distance in .neu / .cgns file.

**Comment by Niceno** [comment]
I believe it is worth a try.
