### ISSUE TITLE
What does 1) mean in commits?

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#44]
I noticed that some files are committed with the comment:

`1)`

What is that supposed to mean?  We have to agree if we are writing understandable comments when committing, or puzzles for fellow developers :-(

**Comment by palkinev** [comment]
It was my mistake.
Commit message was transparent, Bojan, but git website interpreted as "1)".
You can see whole message here:
[https://github.com/DelNov/T-Flows/commit/e5a696101b6bf3f8249e8cd22eefbb6b17335655](link)

**Comment by palkinev** [comment]
And I believe I have fixed that in pull request #45 .

**Comment by Niceno** [comment]
Oh, I believed you started to introduce some new cryptic language :D
