### ISSUE TITLE
Update_Boundary_Values.f90 must be corrected.

### ISSUE THREAD

**Issue by mhadziabdic** [DelNov/T-Flows#5]
Calculation of Twall and heat flux at wall in Update_Boundary_Values.f90 is not correct. I will make corrections and send it for approval.

**Comment by Niceno** [comment]
OK, a few comments:

- "area" doesn't have to be global variable, it is OK to keep it local in this function.

- "heat_flux" (which used to be Qflux) is now part of Flow_Mod.  It think it makes sense, it is one kind of characterization of the flow.  

- In addition to "heat_flux", I also added "heat" to the Flow_Mod.  I am not sure if it is really needed.

- I also find a bit confusing the way "heat_flux" is computed for "WALL" and "WALLFL" conditions, for the case of WALL it is:

heat_flux = heat_flux + t % q(c2)

but for WALLFL is:

heat_flux = heat_flux + t % q(c2) * s_tot

I will carry on fixing, these are comments for Muhamed to consider.

**Comment by mhadziabdic** [comment]
1. Eps does not need to be updated at the wall as it is calculated by its boundary condition which is different than zero, unlike k and stresses. 
2. Agree, no need to have area as global one. 
3. Agree, it is also needed for correction of temperature equation when periodic bc is used.
4. it is useful and can be used to calculate average Nusselt number.
5. I agree, in one case heat flux is constant and heat transfer at each cell is calculated by q * area_cell, in WALL heat flux needs to be computed and in this computation I already included surface, like 
T % q(c2) = s_tot * (T % n(c2) - T % n(c1)) * con_wall   / grid % wall_dist(c1)
so no need to add s_tot. I might be more consistent just to delete s_tot from T % q formula and then to compute heat flux as it is done for WALLFL.

**Comment by palkinev** [comment]
Muhamed, @mhadziabdic , 
I think for now this issue can be closed, it not it?
you can check current state of [Update_Boundary_Values.f90](https://github.com/DelNov/T-Flows/blob/release_branch/Sources/Process/Update_Boundary_Values.f90)

**Comment by mhadziabdic** [comment]
Sorry guys I was out of office today. I will fix Update_Boundary_Values.f90 tomorrow. It is not correct as it is now.
