### ISSUE TITLE
monitoring plane is not defined or defined incorrectly

### ISSUE THREAD

**Issue by palkinev** [DelNov/T-Flows#50]
issue is simple, but consequences are huge

function Control_Mod_Point_For_Monitoring_Plane looks for a keyword "POINT_FOR_MONITORING_PLANE". 
Although **all** test cases for Process has POINT_FOR_MONITORING_PLANE**S**  in control files.

**Comment by Niceno** [comment]
Muhamed and me found where is the problem and will soon upload a fixed version.

**Comment by DelNov** [comment]
It is fixed already
