### ISSUE TITLE
Untie script for makefile dependencies from directory structure

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#59]
Dear Egor,

The script you wrote to extract makefile dependencies is a majestic piece of work.  Your diligence and prudence in handling the problem is astounding.  

Yet, it would be very useful to untie it from T-Flows directory structure.  Like: the doesn't know at all about `GENE_DIR`, `PROC_DIR` and stuff like that, it simply creates `makefile` dependencies for the directory in which it is executed from.  So, if you are in `Divisor`, for example, you run `../Utilities/create_makefile_dependencies.sh` and "voila" ... you get it right there, just for Divisor.  

Would it be difficult to do?

**Comment by palkinev** [comment]
I think your request is fulfilled by pull request #56

**Comment by Niceno** [comment]
Indeed, very good job Egor.
