### ISSUE TITLE
Save_results.f90 is not called for Rans channel flow computation. 

### ISSUE THREAD

**Issue by mhadziabdic** [DelNov/T-Flows#6]
I worked on user function Save_Results.f90 file for channel flow RANS. I finished it but for some reason the file is not called at all. I attached new, debugged function.
[Save_Results.f90.gz](https://github.com/DelNov/T-Flows/files/2046186/Save_Results.f90.gz)

**Comment by Niceno** [comment]
Dear Hamo, could you be more specific?  Which case did you run?

**Comment by mhadziabdic** [comment]
It was stupid problem but I am learning code :). Sorry for posting trivial issue. The user defined Save_Results.f90 was not called at the end of computation but only if you write save_now or exit_now. I added new line in Main_Pro.f90 so this is solved. I will test new implementation of Update_Boundary_Data.f90 and after that I will submit changes for approval.

**Comment by mhadziabdic** [comment]
Guys what will we do with source term we need to have in case of channel flow with periodic boundary conditions and heat transfer? This is case specific since it depends on size of the domain. Should we put this into User_Mod for each case, but it needs to be called within Compute_Temperature.f90. 
This is how I implemented this source for LES in previous version of code:
48     width = 3.14
 49 
 50   if( phi % name == 'T' ) then
 51     if(HOT==YES) then
 52       do m=1,grid % n_materials
 53         if(bulk(m) % p_drop_x > 1.0e-8.or.&
 54            bulk(m) % flux_x_o > 1.0e-8) then
 55           do c = 1, grid % n_cells
 56             b(c) = b(c) - 2.0*U % n(c) * Qflux * width / &
 57                   (CAPc(material(c))*bulk(m) % flux_x) * grid % vol(c)
 58           end do
 59         else if( bulk(m) % p_drop_y > 1.0e-8.or.&
 60                  bulk(m) % flux_y_o > 1.0e-8) then
 61             b(c) = b(c) - V % n(c) * Qflux * width/&
 62                   (CAPc(material(c))*bulk(m) % flux_y) * grid % vol(c)
 63         else if( bulk(m) % p_drop_z > 1.0e-8.or.&
 64                  bulk(m) % flux_z_o > 1.0e-8) then
 65             b(c) = b(c) - W % n(c) * Qflux * width/&
 66                    (CAPc(material(c))*bulk(m) % flux_z) * grid % vol(c)
 67         end if
 68       end do
 69     end if
 70   end if

**Comment by Niceno** [comment]
Sure, it has to be implemented via user functions, I will work on it in Thursday, now I have to run to Zurich to give lectures :-/

**Comment by Niceno** [comment]
Hamo, when you say "mass flux", do you mean mass flux at cell faces or total mass fluxes through domain?  The latter are not even saved in backup files, it would have to be implemented, but it's very simple, I can do it in no time.

**Comment by mhadziabdic** [comment]
Mass flux meaning total mass flux, for channel we put 1.16 and after restart we end up with 0.57 :( . Also I noticed that pressure drop printed on screen is 0 after restart even it should have some finite value. 
When starting computation Az (computational area in z direction) is 0 even point in control file is within the domain.

**Comment by palkinev** [comment]
I noticed that latest accepted pull request  #21 solved this issue
but I do not want to close it at the moment since solution @mhadziabdic  made required to substitute Sources/Process/User_Mod/Save_Results.f90 with a symbolic link.

**Comment by Niceno** [comment]
Hi guys, what is the status of this issue?
