### ISSUE TITLE
Mass flux and pressure drop in channel and pipe

### ISSUE THREAD

**Issue by mhadziabdic** [DelNov/T-Flows#67]
This issue was arose some time ago and it was fixed but somehow it reemerges in the latest version (I did not know if it exists in the version prior to this one). When computing channel flows with periodic boundary conditions, pressure drop printed on screen is imposed one but not calculated one, both for RANS and LES computations. In LES computations of channel flow mass flux that appears in the screen is not the same as the imposed one which should not be.

**Comment by Niceno** [comment]
Hmm, I am trying the:

'''Rans/Channel_Re_Tau_590/Stretched_Mesh'''

and it seems fine to me.
