### ISSUE TITLE
Les/Pipe_Re_Tau_180 problems with DEBUG and output

### ISSUE THREAD

**Issue by palkinev** [DelNov/T-Flows#70]
I am appreciated that WallDistance for Les/Pipe_Re_Tau_180 case is fine after Divide now, but there are still more problems with it:

1) If you launch Process compiled with "make DEBUG=yes" in Les/Pipe_Re_Tau_180 test case you will get NaN from first time step.

2) User functions for this test case ignore for some reason pipe.1d file and DO NOT produce any output files to compare it with DNS via gnuplot and test_build.sh.

**Comment by Niceno** [comment]
I did some checking and found that that 1. happens for `les_dynamic only`, `les_smagorinsky` works
