### ISSUE TITLE
-lz option is still in Generator/makefile

### ISSUE THREAD

**Issue by MassimoBorrelliPhysicist** [DelNov/T-Flows#74]
We dropped support for gzip libraries (-lz option) but it's still in Generator's makefile.

**Comment by palkinev** [comment]
I do not confirm that "-lz" is still present:
![screenshot_2018-11-14_16-31-35](https://user-images.githubusercontent.com/31729290/48473332-d1be9a00-e82a-11e8-9705-d4dcc7ebbfe8.png)

Please, keep your local git source updated with remote DelNov repository.

**Comment by Niceno** [comment]
Hmm ... I just assigned this issue to myself, but it seems the issue was that Massimo was not using the latest sources, right?

**Comment by palkinev** [comment]
right, 
remember to git pull sources from delnov before you want to start coding and raising issues.

**Comment by Niceno** [comment]
How do you pull sources to your fork from upstream repository?  I am trying form almost two hours, but without success.  The best I managed to do is to switch from one fork to another.  But to compare them or pull changes - no way :sob:

**Comment by palkinev** [comment]
To pull the code from someone's fork repository you have type:
`git pull name_of_desired_fork_to_pull_from  name_of_the_branch_you_want_to_pull`

But **name_of_desired_fork_to_pull_from** is a local name, known only to your local git.
You can set any name you like.
In my case I named your forks "bojan", "massimo", "delnov", "egor".

This command will output names of local known forks:
`git remote -v`

bojan	https://github.com/Niceno/T-Flows (fetch)
bojan	https://github.com/Niceno/T-Flows (push)
delnov	https://github.com/DelNov/T-Flows (fetch)
delnov	https://github.com/DelNov/T-Flows (push)
egor	https://github.com/palkinev/T-Flows (fetch)
egor	https://github.com/palkinev/T-Flows (push)
massimo	https://github.com/MassimoBorrelliPhysicist/T-Flows (fetch)
massimo	https://github.com/MassimoBorrelliPhysicist/T-Flows (push)

You can see that at the moment my local git is not aware of Muhamed's fork.

Thus, if I want to pull the code from Muhamed's branch **release_branch** from repository I need to do the following:

`git remote add muhamed https://github.com/mhadziabdic/T-Flows-1`
`git pull muhamed release_branch`

**Comment by Niceno** [comment]
But I believe that this issue can be closed now.
