### ISSUE TITLE
readme.md or README.md?

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#80]
Dear all,

Our `readme.md`, which we can see on the main DelNov page: https://github.com/DelNov/T-Flows

is still not as good looking as `README.md` which I have in my fork: https://github.com/Niceno/T-Flows-Last-Amg

Could it be that github accepts formatting commands in `.md` (stands for **m**ark**d**own) files only if they are called with capital letters?

**Comment by palkinev** [comment]
After sign "#" git expects 1 space.

# The largest heading
## The second largest heading
###### The smallest heading

**Comment by Niceno** [comment]
It is fixed, I believe it can be closed.
