### ISSUE TITLE
Test for Hybrid model must be extended for a range of Re numbers

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#85]
Hi guys,

At present we have two tests for Hybrid model, one on uniform, one for stretched grid.  However, it would be very advantageous and convincing if we had many Reynolds numbers.  Connected to that, I have some concerns:
1.  If we are going to provide cases for a number of Re numbers, what shall we put as data to compare with?  I assume some DNS databases, right?
2.  If we are going for DNS databases, which would they be?  At the time when I was a PhD student there was a database for Re_Tau=180, Re_Tau=590 came a bit later, and after my graduation I also saw Re_Tau=1080.  Anything newer and bigger on the market?

Cheers

**Comment by palkinev** [comment]
Last time I searched for DNS Channel database it was Re_tau = 2300+.

**Comment by mhadziabdic** [comment]
In my thesis I have results for Re_tau = 20 000 so I am not sure that we
will gain much with different Re number for channel. It is much more
exciting to show that the model is working very well in wall function mode.
What we would need is hybrid model in some other configuration such as
impinging jet or backstep.
Assoc. Prof. Muhamed Hadziabdic
Mech. Engineering Program Coordinator
Faculty of Engineering and Natural Sciences
International University of Sarajevo
Hrasnicka cesta 15, 71210, Ilidza, Sarajevo

mob. +387 61 228 489
mail: mhadziabdic@ius.edu.ba

**Comment by Niceno** [comment]
I would run different Re numbers (three at least) to convince some people at PSI to use T-Flows.  So ... maybe I will say something stupid, but I reckon it would be nice if we had:
* Re_Tau = 590
* Re_Tau = 1080 (I think there was such a database)
* Re_Tau = 2300 (the one Egor suggests)

Egor, what is the database you are referring to?  Is there a reference?

**Comment by Niceno** [comment]
I was peeking around a little bit to find a DNS database we could use.  I encountered a few, but this one Politechnical University of Madrid seems to be the most comprehensive for our needs: 
https://torroja.dmt.upm.es/channels/data/

Do you guys know anything about it?  Is this database cited, acknowledged, praised?

**Comment by mhadziabdic** [comment]
Jimenez is well known name in LES community and Physics of Fluid is a good
journal. So I think this is reliable source.

Cheers.

Hamo

Assoc. Prof. Muhamed Hadziabdic
Mech. Engineering Program Coordinator
Faculty of Engineering and Natural Sciences
International University of Sarajevo
Hrasnicka cesta 15, 71210, Ilidza, Sarajevo

mob. +387 61 228 489
mail: mhadziabdic@ius.edu.ba
