### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#89]
Dear all,

I peaked in the github repository from Code Saturne: https://github.com/code-saturne/code_saturne and saw they have a number of keywords in their page.  What do you think about it?  Shall we do the same?  I guess keywords help to get noticed, right?

**Comment by mhadziabdic** [comment]
Good idea, I suggest to do the same.

**Comment by Niceno** [comment]
I don't know how to do it :-(
