### ISSUE TITLE
In Compute_Turbulent.f90 

### ISSUE THREAD

**Issue by MassimoBorrelliPhysicist** [DelNov/T-Flows#92]
Dear all,
I am now writing a source code to implement the theta2 equation we discussed some time ago. To this end, I am using Compute_Turbulent.f90 as a guide. While browsing through it I came across the a strange if statement at line 105

105 if(c2 > 0) then

What I do not understand is that, a few lines (118) below and still inside this if structure, the following statement appears

118  if(c2  > 0) then
119        phi % a(c1) = phi % a(c1)-flux(s) * phis    
120        phi % a(c2) = phi % a(c2)+flux(s) * phis
121      else
122        phi % a(c1) = phi % a(c1)-flux(s) * phis
123  end if

I am having a hard time following the logic here and maybe this is a stupid question, but doesn't the else at line 121 contradict the first if at line 105? I ask because if you instead look at Compute_Energy.f90 this feature is not present.

Thanks in advance,

Massimo

**Comment by palkinev** [comment]
It remains of the previous  code. (attached below)
line 105 you mentioned was formed from the line
"c2  > 0 .or. c2  < 0.and.TypeBC(c2) == BUFFER"

Bojan changed the way how buffer are defined.
Previously it was pure boundary cells, had indices below 0 and b.c. type "buffer".
Thus, for internal domain we had c2>0 and c2  < 0.and.TypeBC(c2) == BUFFER subdomains.

I suppose Bojan deleted buffer key word and line 105 had to be changed in order to compile the code.

```
  do s=1,NS

    c1=SideC(1,s)
    c2=SideC(2,s) 

!----- velocities on "orthogonal" cell centers 
    if(c2  > 0 .or. c2  < 0.and.TypeBC(c2) == BUFFER) then
      PHIs=f(s)*PHI % n(c1) + (1.0-f(s))*PHI % n(c2)

    if(BLEND_TUR(material(c1)) /= NO .or. BLEND_TUR(material(c2)) /= NO) then
      call ConvScheme(PHIs, s, PHI % n, dPHIdx, dPHIdy, dPHIdz, Dx, Dy, Dz, &
                      max(BLEND_TUR(material(c1)),BLEND_TUR(material(c2))) ) 
    end if 

!---- Central differencing for convection 
      if(ini == 1) then 
  if(c2  > 0) then
    PHI % Co(c1)=PHI % Co(c1)-Flux(s)*PHIs
    PHI % Co(c2)=PHI % Co(c2)+Flux(s)*PHIs
  else
    PHI % Co(c1)=PHI % Co(c1)-Flux(s)*PHIs
  endif 
      end if
      if(c2  > 0) then
  PHI % C(c1)=PHI % C(c1)-Flux(s)*PHIs
  PHI % C(c2)=PHI % C(c2)+Flux(s)*PHIs
      else
  PHI % C(c1)=PHI % C(c1)-Flux(s)*PHIs
      endif 

!---- Upwind 
      if(BLEND_TUR(material(c1)) /= NO .or. BLEND_TUR(material(c2)) /= NO) then
        if(Flux(s)  < 0) then   ! from c2 to c1
          PHI % X(c1)=PHI % X(c1)-Flux(s)*PHI % n(c2)
          if(c2  > 0) then
            PHI % X(c2)=PHI % X(c2)+Flux(s)*PHI % n(c2)
          endif
        else 
          PHI % X(c1)=PHI % X(c1)-Flux(s)*PHI % n(c1)
          if(c2  > 0) then
            PHI % X(c2)=PHI % X(c2)+Flux(s)*PHI % n(c1)
          endif
        end if
      end if   ! BLEND_TUR 
  end do    ! through sides
```

**Comment by MassimoBorrelliPhysicist** [comment]
Dear Egor,

thanks for quick and the detailed answer. If I understood correctly, c2<0 still represents boundary cells, doesn't it?

**Comment by palkinev** [comment]
I believe that currently we have mostly  2 kinds of loops:
```
do c = 1, grid % n_cells
end do
```
and
```
do s = 1, grid % n_faces
    c1 = grid % faces_c(1,s)
    c2 = grid % faces_c(2,s)
end do
```
For first loop cells in range:
[1, grid % n_cells - grid % comm % n_buff_cells] are internal without buffer zone

[1, grid % n_cells] are internal with buffer zones

[1, grid % n_cells] are internal with buffer zones

[-grid % n_bnd_cells, -1] are cells on boundaries (mid point of a cell face)

For second loop c2<0 are boundary cells and c1>0 are internal with buffers.

As far as I know you can not identify a buffer cell inside this loop anymore.

**Comment by Niceno** [comment]
Yes, boundary cells still have negative indexes.  (They are planar too - have no volume)

But buffer cells (those belonging to other processors) are not any longer treated as additional boundary cells, but rather as additional cells inside domain, hence with positive indexes.  This allowed to simplify a **number** of loops in the code :-)

Massimo, if you are happy with our answers, can we close this issue?

**Comment by Niceno** [comment]
Just to add a few cents to Egors answers.

You can still browse through buffer cells, if you ever want that, by:

```
do c = grid % n_cells - grid % comm % n_buff_cells + 1,   &
       grid % n_cells
  print *, 'Woo-hoo!  I love to be in the buffer!'
end do
```

**Comment by MassimoBorrelliPhysicist** [comment]
Hi all,

yeah it can be closed for me, I thought it had been already :-)

Massimo
