### ISSUE TITLE
How do we remove unused branches?

### ISSUE THREAD

**Issue by Niceno** [DelNov/T-Flows#99]
Dear all,

I think we should remove the branches which we don't use.  For example. neu_bux_fix was resolved by me (to my firm belief) and is not just hanging around.  The same is probably also true for mhadziabdic-patch-1.

Any advice or opinion would be appreciated.

**Comment by palkinev** [comment]
You can simply push red bin button in branches list after merge is complete.

![screenshot_2019-02-04_16-02-07](https://user-images.githubusercontent.com/31729290/52198773-88647080-2896-11e9-8959-17e6079ef0b1.png)

**Comment by Niceno** [comment]
Woo-hoo - thanks a lot.  Lubomir also helped me.
